export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_FILTERED_PRODUCT = 'SET_FILTERED_PRODUCT';
export const SET_HEADER = 'SET_HEADER';
export const SET_SHOW_TABLE = 'SET_SHOW_TABLE';
export const SET_EDIT_TABLE = 'SET_EDIT_TABLE';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TABLE_SIZE = 'SET_TABLE_SIZE';